# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='celulares',
            fields=[
                ('idprod', models.AutoField(primary_key=True, serialize=False)),
                ('ce_marca', models.CharField(max_length=15)),
                ('ce_model', models.CharField(max_length=13)),
                ('ce_desc', models.CharField(max_length=30)),
            ],
        ),
    ]
