# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('c_nomb', models.CharField(max_length=20)),
                ('c_telf', models.CharField(max_length=10)),
                ('c_dir', models.CharField(max_length=15)),
            ],
        ),
    ]
