# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celulares', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_compra', models.DateTimeField(blank=True)),
                ('c_num', models.CharField(max_length=10)),
                ('c_dni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('ce_idprod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='celulares.celulares')),
            ],
        ),
    ]
